spring:
  datasource:
    # 数据库访问配置, 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #链接池配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ip:port/数据库名?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#      url: jdbc:mysql://127.0.0.1:3306/ue_sys?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: 账号
#      username: root
      password: 密码
#      password: 159567

      # 连接池配置：大小，最小，最大
      initial-size: 1
      min-idle: 1
      max-active: 20

  #启用Restful风格访问
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:/

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8888
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
